# Generated by Django 5.2.3 on 2025-07-03 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_date'], name='blog_post_created_16bfbe_idx'),
        ),
    ]
