# Generated by Django 5.2.3 on 2025-07-03 15:05

import blog.customevalidators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_blog_post_created_16bfbe_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Quantity must be at least 0'), django.core.validators.MaxValueValidator(500, message='Quantity must be execed 100')])),
                ('classCode', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(db_column='firstName', max_length=20)),
                ('LastName', models.CharField(db_column='lastname', max_length=20)),
                ('Address', models.TextField(blank=True, max_length=12, null=True, validators=[blog.customevalidators.validate_11_digit_phone])),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Dore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.dore')),
            ],
        ),
    ]
