# Generated by Django 5.2.3 on 2025-07-03 15:12

import blog.customevalidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_dore_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='PhoneNumber',
            field=models.CharField(max_length=15, validators=[blog.customevalidators.validate_11_digit_phone]),
        ),
    ]
