# Generated by Django 4.2.25 on 2025-10-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book', max_length=300)),
                ('author', models.CharField(help_text='Author(s) of the book', max_length=200)),
                ('isbn', models.CharField(blank=True, help_text='International Standard Book Number', max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description or summary of the book', null=True)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('history', 'History'), ('self-help', 'Self-Help'), ('business', 'Business'), ('technology', 'Technology'), ('other', 'Other')], default='other', help_text='Genre/category of the book', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('ar', 'Arabic'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('other', 'Other')], default='en', help_text='Language of the book', max_length=10)),
                ('publisher', models.CharField(blank=True, help_text='Publisher of the book', max_length=200, null=True)),
                ('publication_date', models.DateField(blank=True, help_text='Date when the book was published', null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages in the book', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the book', max_digits=10, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='book_covers/')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the book is currently available')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Number of copies available in stock')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['title'], name='blog_book_title_41da13_idx'), models.Index(fields=['author'], name='blog_book_author_9dd427_idx'), models.Index(fields=['genre'], name='blog_book_genre_8e9f3e_idx'), models.Index(fields=['is_available'], name='blog_book_is_avai_3ca976_idx'), models.Index(fields=['-created_date'], name='blog_book_created_46d6a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('body', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='blog_commen_created_0e6ed4_idx')],
            },
        ),
    ]
