# Generated by Django 5.2.7 on 2025-12-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_book_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dore',
            name='student',
            field=models.ManyToManyField(to='blog.students'),
        ),
    ]
