# Generated by Django 5.2.7 on 2025-12-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_dore_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Dore',
        ),
    ]
