# Generated by Django 5.2.7 on 2025-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_students_dore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dore',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
