# Generated by Django 5.2.7 on 2025-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_dore_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dore',
            name='room_number',
            field=models.IntegerField(blank=True, choices=[(101, '101'), (102, '102'), (103, '103'), (201, '201')], null=True),
        ),
    ]
