# Generated by Django 5.2.7 on 2025-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_dore_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dore',
            name='room_number',
        ),
        migrations.AddField(
            model_name='dore',
            name='service',
            field=models.CharField(blank=True, choices=[('ssh', 'Ssh'), ('web', 'Web'), ('ping', 'Ping')], null=True),
        ),
    ]
