# Generated by Django 5.2.7 on 2025-12-05 08:31

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_dore_room_number_dore_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='dore',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dore',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dore',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 12, 5, 8, 31, 25, 379032, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
