# Generated by Django 5.2.7 on 2025-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTamrin', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=False)),
                ('mtu', models.PositiveIntegerField(default=1500)),
                ('interface_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('wireless', 'Wireless'), ('virtual', 'Virtual'), ('other', 'Other')], default='ethernet', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
